apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: database-backup
  namespace: storage
spec:
  schedule: "1 9,21 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cron-database-backup
              image: sa-saopaulo-1.ocir.io/grwidfxfmi4f/kubernetes-database-backup:latest
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: 600m
                  memory: 1Gi
              env:
                - name: TZ
                  value: America/Sao_Paulo
                - name: MONGODB_BACKUP
                  value: "1"
                - name: MYSQL_BACKUP
                  value: "1"
                - name: S3_BUCKET_BACKUP
                  value: 
                - name: S3_MONGODB_BUCKET_PATH
                  value: database/mongodb
                - name: S3_MYSQL_BUCKET_PATH
                  value: database/mysql
                - name: MYSQL_ROTATE_ARGS
                  value: "--hourly=24 --daily=7 --weekly=10 --monthly=12 --yearly=always"
                - name: MONGODB_ROTATE_ARGS
                  value: "--hourly=24 --daily=7 --weekly=10 --monthly=12 --yearly=always"
                - name: AWS_DEFAULT_REGION
                  valueFrom:
                    secretKeyRef:
                      name: 
                      key: 
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: 
                      key: 
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: 
                      key: 
                # MongoDB
                - name: MONGODB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: 
                      key: 
                - name: MONGODB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: 
                      key: 
                - name: MONGODB_HOST
                  valueFrom:
                    secretKeyRef:
                      name:
                      key:
                - name: MONGODB_PORT
                  value: "27017"
                - name: MONGODB_AUTH_DB
                  value: admin
                  # OR
                - name: MONGODB_URI
                  value: "mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@$(MONGODB_HOST)"

                # MySQL
                - name: MYSQL_HOST
                  valueFrom:
                    secretKeyRef:
                      name: 
                      key: 
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: 
                      key: 
                - name: MYSQL_ROOT_USERNAME
                  value: root
