
nodeSelector: {}

### Container size (request/limits)
resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 1Gi

## Container image confs
image:
  repository: gru.ocir.io/grwidfxfmi4f/kubernetes-database-backup
  tag: latest
  pullPolicy: IfNotPresent
  # pullSecret: registry-secret

schedule: 1 9 * * *
concurrencyPolicy: Forbid
successfulJobsHistoryLimit: 1
failedJobsHistoryLimit: 3
# customCommand: sleep 60

## Enviroment variables
extraEnv:
  - name: TZ
    value: "America/Sao_Paulo"
  - name: LOG_LEVEL
    value: debug
    
  - name: FAST_COMPRESSION
    value: "1"
  - name: REPORT_SUCCESSFULLY
    value: "0"

  - name: ROTATE_ARGS
    value: "--hourly 24 --daily 7 --weekly 10 --monthly 12 --yearly 10 -D"

  # - name: S3_BUCKET_BACKUP
  #   value: 
  
  # - name: AWS_REGION
  #   valueFrom:
  #     secretKeyRef:
  #       name: 
  #       key: 
  # - name: AWS_ACCESS_KEY_ID
  #   valueFrom:
  #     secretKeyRef:
  #       name: 
  #       key: 
  # - name: AWS_SECRET_ACCESS_KEY
  #   valueFrom:
  #     secretKeyRef:
  #       name: 
  #       key: 
  
  # MongoDB
  # - name: MONGODB_BACKUP
  #   value: "1"
  # - name: MONGODB_S3_BUCKET_PATH
  #   value: database/mongodb
  # - name: MONGODB_USERNAME
  #   valueFrom:
  #     secretKeyRef:
  #       name: 
  #       key: 
  # - name: MONGODB_PASSWORD
  #   valueFrom:
  #     secretKeyRef:
  #       name: 
  #       key: 
  # - name: MONGODB_HOST
  #   valueFrom:
  #     secretKeyRef:
  #       name:
  #       key:
  # - name: MONGODB_PORT
  #   value: "27017"
  # - name: MONGODB_AUTH_DB
  #   value: admin
  #   # OR
  # - name: MONGODB_URI
  #   value: "mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@$(MONGODB_HOST)"

  # MySQL
  # - name: MYSQL_BACKUP
  #   value: "1"
  # - name: MYSQL_S3_BUCKET_PATH
  #   value: database/mysql
  # - name: MYSQL_IGNORE_DATABASES
  #   value: "information_schema performance_schema mysql sys mysql_audit"
  # - name: MYSQL_HOST
  #   valueFrom:
  #     secretKeyRef:
  #       name: 
  #       key: 
  # - name: MYSQL_ROOT_PASSWORD
  #   valueFrom:
  #     secretKeyRef:
  #       name: 
  #       key: 
  # - name: MYSQL_ROOT_USERNAME
  #   value: root

  # PostgreSQL
  # - name: PGSQL_BACKUP
  #   value: "1"
  # - name: PGSQL_S3_BUCKET_PATH
  #   value: database/postgresql
  # - name: PGSQL_IGNORE_DATABASES
  #   value: postgres rdsadmin
  # - name: PGSQL_HOST
  #   value: 
  # - name: PGSQL_USERNAME
  #   value:
  # - name: PGSQL_PASSWORD
  #   valueFrom:
  #     secretKeyRef:
  #       name: 
  #       key: 
