apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backup-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- $localDict := dict "previous" "-"}}
{{- range $path, $bytes  := .Files.Glob "scripts/*" }}
  {{ $path | base }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
