#!/bin/bash
set -e

readonly BACKUP_PATH="/backup/auto"
readonly TIMESTAMP=$(date +%F-%H%M)
readonly TAR_FILE="mysql-${TIMESTAMP}.tar.gz"

do_log() {
    echo $(date +"[ %d/%m/%Y - %H:%M:%S ] #")" $@"
}

notify_dev() {
    # Adicione aqui uma forma de notificação quando o backup for concluido ou tiver erro
    # Ex.:
    # curl --fail --silent --request POST $NTFY_ENDPOINT \
    #     --header "x-api-key: ${NTFY_TOKEN}" \
    #     --header 'Content-Type: application/json' \
    #     --data-raw "{\"subject\": \"${1}\",\"message\": \"${2}\",\"topic\":\"mail\"}"
}

do_log "Starting backup MySQL..."

# Create a backup dir
mkdir -p $BACKUP_PATH
cd $BACKUP_PATH

# mysqldump para exportar a database
mysqldump --host=$MYSQL_HOST --user=$MYSQL_ROOT_USERNAME --password="${MYSQL_ROOT_PASSWORD}" --all-databases > $BACKUP_PATH/backup.sql

if [[ $? != 0 ]]; then
    do_log "ERROR backup"
    do_log "Dumping of mysql database failed"
    do_log "Cleanup old backup $BACKUP_PATH"

    notify_dev "Warning MySQL Backup $TIMESTAMP" "MySQL Backup: ERROR on export data"
    rm -rf "$BACKUP_PATH/*"
    exit 1
fi

tar -czf /tmp/${TAR_FILE} -C ${BACKUP_PATH} ${BACKUP_PATH}/backup.sql

du -hs $BACKUP_PATH
du -hs /tmp/$TAR_FILE

do_log "Cleanup old backup /backup/auto"
rm -rf "$BACKUP_PATH/*"

# Upload to S3
do_log "Upload file on s3 s3://$S3_BUCKET_BACKUP/$S3_MYSQL_BUCKET_PATH/$TAR_FILE"
aws s3 cp /tmp/$TAR_FILE  s3://$S3_BUCKET_BACKUP/$S3_MYSQL_BUCKET_PATH/$TAR_FILE

UPLOAD_STATUS=$?

do_log "Remove tar file"
rm -f /tmp/$TAR_FILE

if [[ $UPLOAD_STATUS != 0 ]]; then
    do_log "ERROR Upload tar /tmp/$TAR_FILE on s3 fail"
    notify_dev "Warning MySQL Backup $TIMESTAMP" "MySQL Backup: ERROR Upload tar /tmp/$TAR_FILE to S3"
else
    do_log "Success upload tar /tmp/$TAR_FILE to S3"
    notify_dev "MySQL Backup $TIMESTAMP" "MySQL Backup finished successfully $TAR_FILE"
fi

exit $?
